package com.sgm.hsearch.entity;

import java.util.Date;

public class HsDocument {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.VISIT_COUNT
     *
     * @mbggenerated
     */
    private Long visitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.CREATED_ON
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.UPDATED_ON
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.KEYWORDS
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.CLASSFY
     *
     * @mbggenerated
     */
    private String classfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.ENABLE
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.ABSTRACTS
     *
     * @mbggenerated
     */
    private String abstracts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TT_DOCUMENT.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.ID
     *
     * @return the value of HS_TT_DOCUMENT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.ID
     *
     * @param id the value for HS_TT_DOCUMENT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.TITLE
     *
     * @return the value of HS_TT_DOCUMENT.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.TITLE
     *
     * @param title the value for HS_TT_DOCUMENT.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.PATH
     *
     * @return the value of HS_TT_DOCUMENT.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.PATH
     *
     * @param path the value for HS_TT_DOCUMENT.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.VISIT_COUNT
     *
     * @return the value of HS_TT_DOCUMENT.VISIT_COUNT
     *
     * @mbggenerated
     */
    public Long getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.VISIT_COUNT
     *
     * @param visitCount the value for HS_TT_DOCUMENT.VISIT_COUNT
     *
     * @mbggenerated
     */
    public void setVisitCount(Long visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.CREATED_ON
     *
     * @return the value of HS_TT_DOCUMENT.CREATED_ON
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.CREATED_ON
     *
     * @param createdOn the value for HS_TT_DOCUMENT.CREATED_ON
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.CREATED_BY
     *
     * @return the value of HS_TT_DOCUMENT.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.CREATED_BY
     *
     * @param createdBy the value for HS_TT_DOCUMENT.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.UPDATED_ON
     *
     * @return the value of HS_TT_DOCUMENT.UPDATED_ON
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.UPDATED_ON
     *
     * @param updatedOn the value for HS_TT_DOCUMENT.UPDATED_ON
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.UPDATED_BY
     *
     * @return the value of HS_TT_DOCUMENT.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.UPDATED_BY
     *
     * @param updatedBy the value for HS_TT_DOCUMENT.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.KEYWORDS
     *
     * @return the value of HS_TT_DOCUMENT.KEYWORDS
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.KEYWORDS
     *
     * @param keywords the value for HS_TT_DOCUMENT.KEYWORDS
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.CLASSFY
     *
     * @return the value of HS_TT_DOCUMENT.CLASSFY
     *
     * @mbggenerated
     */
    public String getClassfy() {
        return classfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.CLASSFY
     *
     * @param classfy the value for HS_TT_DOCUMENT.CLASSFY
     *
     * @mbggenerated
     */
    public void setClassfy(String classfy) {
        this.classfy = classfy == null ? null : classfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.ENABLE
     *
     * @return the value of HS_TT_DOCUMENT.ENABLE
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.ENABLE
     *
     * @param enable the value for HS_TT_DOCUMENT.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.ABSTRACTS
     *
     * @return the value of HS_TT_DOCUMENT.ABSTRACTS
     *
     * @mbggenerated
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.ABSTRACTS
     *
     * @param abstracts the value for HS_TT_DOCUMENT.ABSTRACTS
     *
     * @mbggenerated
     */
    public void setAbstracts(String abstracts) {
        this.abstracts = abstracts == null ? null : abstracts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TT_DOCUMENT.CONTENT
     *
     * @return the value of HS_TT_DOCUMENT.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TT_DOCUMENT.CONTENT
     *
     * @param content the value for HS_TT_DOCUMENT.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}