package com.sgm.hsearch.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.ENG_NAME
     *
     * @mbggenerated
     */
    private String engName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.CHIN_NAME
     *
     * @mbggenerated
     */
    private String chinName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.OVSD_NAME
     *
     * @mbggenerated
     */
    private String ovsdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.SHIFT
     *
     * @mbggenerated
     */
    private String shift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.EMP_NUMER
     *
     * @mbggenerated
     */
    private String empNumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.CREATED_ON
     *
     * @mbggenerated
     */
    private Date createdOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.UPDATED_ON
     *
     * @mbggenerated
     */
    private Date updatedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_TM_USER.ENABLE
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.ID
     *
     * @return the value of HS_TM_USER.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.ID
     *
     * @param id the value for HS_TM_USER.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.LOGIN_NAME
     *
     * @return the value of HS_TM_USER.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.LOGIN_NAME
     *
     * @param loginName the value for HS_TM_USER.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.ENG_NAME
     *
     * @return the value of HS_TM_USER.ENG_NAME
     *
     * @mbggenerated
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.ENG_NAME
     *
     * @param engName the value for HS_TM_USER.ENG_NAME
     *
     * @mbggenerated
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.CHIN_NAME
     *
     * @return the value of HS_TM_USER.CHIN_NAME
     *
     * @mbggenerated
     */
    public String getChinName() {
        return chinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.CHIN_NAME
     *
     * @param chinName the value for HS_TM_USER.CHIN_NAME
     *
     * @mbggenerated
     */
    public void setChinName(String chinName) {
        this.chinName = chinName == null ? null : chinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.OVSD_NAME
     *
     * @return the value of HS_TM_USER.OVSD_NAME
     *
     * @mbggenerated
     */
    public String getOvsdName() {
        return ovsdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.OVSD_NAME
     *
     * @param ovsdName the value for HS_TM_USER.OVSD_NAME
     *
     * @mbggenerated
     */
    public void setOvsdName(String ovsdName) {
        this.ovsdName = ovsdName == null ? null : ovsdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.SHIFT
     *
     * @return the value of HS_TM_USER.SHIFT
     *
     * @mbggenerated
     */
    public String getShift() {
        return shift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.SHIFT
     *
     * @param shift the value for HS_TM_USER.SHIFT
     *
     * @mbggenerated
     */
    public void setShift(String shift) {
        this.shift = shift == null ? null : shift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.EMP_NUMER
     *
     * @return the value of HS_TM_USER.EMP_NUMER
     *
     * @mbggenerated
     */
    public String getEmpNumer() {
        return empNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.EMP_NUMER
     *
     * @param empNumer the value for HS_TM_USER.EMP_NUMER
     *
     * @mbggenerated
     */
    public void setEmpNumer(String empNumer) {
        this.empNumer = empNumer == null ? null : empNumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.CREATED_ON
     *
     * @return the value of HS_TM_USER.CREATED_ON
     *
     * @mbggenerated
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.CREATED_ON
     *
     * @param createdOn the value for HS_TM_USER.CREATED_ON
     *
     * @mbggenerated
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.UPDATED_ON
     *
     * @return the value of HS_TM_USER.UPDATED_ON
     *
     * @mbggenerated
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.UPDATED_ON
     *
     * @param updatedOn the value for HS_TM_USER.UPDATED_ON
     *
     * @mbggenerated
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_TM_USER.ENABLE
     *
     * @return the value of HS_TM_USER.ENABLE
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_TM_USER.ENABLE
     *
     * @param enable the value for HS_TM_USER.ENABLE
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}